blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Create new issue
    url: http://new-issue.ant.design?repo=ant-design-mobile-rn
    about: The issue which is not created via http://new-issue.ant.design will be closed immediately.
  - name: ğŸ› åˆ›å»ºä¸€ä¸ªé”™è¯¯æŠ¥å‘Šissue
    url: https://github.com/ant-design/ant-design-mobile-rn/issues/new?assignees=1uokun&labels=BugğŸ›&template=bug_report.yml&title=%5BBUG%5D
    about: ä¸ä½¿ç”¨æ¨¡ç‰ˆåˆ›å»ºçš„issueå¯èƒ½ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚