blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Create new issue
    url: https://github.com/ant-design/ant-design-mobile-rn/issues/new?expand=1&template=ISSUE_TEMPLATE.md
    about: A good question can help us quickly locate the problem for you.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: http://new-issue.ant.design?repo=ant-design-mobile-rn
    about: é€šè¿‡æ¨¡ç‰ˆå¯ä»¥å¿«é€Ÿåˆ›å»ºissueï¼Œå¹¶ä¸”èƒ½å¤Ÿå¸®åŠ©æˆ‘ä»¬æ›´å¿«å®šä½é—®é¢˜ã€‚